include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sort_pub_dependencies: false
    prefer_relative_imports: true

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    sort_unnamed_constructors_first: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    avoid_print: ignore
    deprecated_member_use: ignore
  exclude:
    - test/generated/**
    - "**/**.g.dart"
    - "**/**.freezed.dart"
